### ISSUE TITLE
Improvement Items Checklist

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#253]
Start tracking improvement items identified in Sprint Planning calls (or elsewhere) in Coda. 

- [x] Pull prior improvement recommendations into checklist
- [x] Review plan of addressing them with Jason
- [x] Implement process of continually updating the list and taking action

**Comment by jkarpen** [comment]
Notes from 11/27 1:1 with Jason about this:
    * See if there is a way to pull out bullets and turn them into rows automatically
    * Think about how to create a view (maybe with checkboxes list) of things that need to be improved and how to track them
    * End state: get a prioritized list of things we have not done from the improvements recommendations
    * Maybe use new Coda feature to embed tables in other tables? Then that would be linked to the place we take notes (would need to restructure the notes page)
    * Josh - create a checklist of the items, then get with Jason to prioritize how to actually improve them
