### ISSUE TITLE
MDSA Retro Follow-on: Create handoff planning checklist

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#302]
- [ ] Checklist for procurement based on issues that cropped up in the past (license level, validate start date, etc)
- [ ] Develop handoff guide for client (especially for clients handling their own procurement)
- [x] Make sure to include procurement officials in discussions early (include this in checklist)

Should contain checklist and processes that we want to follow for handoff - use this as a starting point https://docs.google.com/document/d/1G9WJgMBk28PsYhgcmwNericIAieCptTia7IzC6RmYNc/edit#heading=h.r7d6m7o78jm

Also look at what Ian created for CARB

**Comment by jkarpen** [comment]
@jasonlally I could use your input on this since it is procurement related and you have the most expertise there. I added it to our 1:1 list for this week.

**Comment by jkarpen** [comment]
@jasonlally here is the template doc for you to fill in with procurement details: https://docs.google.com/document/d/1vSW3wvI8uSdagwI-StCwRYppxDLPZCKoVSM7HXUnDsA/edit

**Comment by jkarpen** [comment]
Draft handoff guide doc has been shared with the Caltrans team, closing this as complete. Any additional updates will go in a new issue.
