### ISSUE TITLE
Create Risk Tracking Table in Coda

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#313]
Populate a risk tracking table in Coda following the template provided by Anusha. 

Anusha's template: https://docs.google.com/spreadsheets/d/14fp3Y-YVdmqBIY4tweTlE7kxRimxa8mi/edit#gid=1516133263

- [x] Create table in Coda
- [x] Populate with risks from Caltrans premortem, oversight doc

From Jason: would be valuable to differentiate between risks to the project vs. risks to implementation.

**Comment by jkarpen** [comment]
Created blank table here: https://coda.io/d/Data-Services-Engineering_dY5Oul8-jdi/Risk-Tracking-Table_su86t#_lurJQ

**Comment by jkarpen** [comment]
The Risk Tracking table is setup in Coda (see link in comment above) but I had not had a chance to populate it yet. I was planning to take the risks from the following docs:

- [ ] Caltrans premortem doc: https://www.figma.com/board/geIIjKEmgv8IBsXPAkXetf/Caltrans-Premortem-Page?node-id=0-1&t=kpayGQhYAmcwVeXN-0
- [ ] Caltrans leadership call running notes (has table of risks at the top of doc): https://docs.google.com/document/d/1mQbsnGlTQXipUUxSaZfMNxpHvGWaYDLIIWR7fLLe4eU/edit?pli=1#heading=h.h3wl1g15cmu9
- [ ] CARB oversight call running notes doc (table of risks at top of doc): https://docs.google.com/document/d/1f1XdmfGzcTccxvixtDoevQYdyiRfPMQdwH-jQVZXSzQ/edit?pli=1#heading=h.h3wl1g15cmu9
- [ ] Sprint Planning Coda notes page - I recently added a section at the bottom for asking about risks. Check the last 2 or 3 sessions, I think one or two of them will have risks the team identified. https://coda.io/d/Data-Services-Engineering_dY5Oul8-jdi/Sprint-Planning_suVBG#Sprint-Retros_tuYa8/r23

**Comment by jkarpen** [comment]
@junlee-analytica Could you link here to the risk tracking template you created last week?

**Comment by junlee-analytica** [comment]
[Risk Register High Level Template.pptx](https://github.com/user-attachments/files/15962168/Risk.Register.High.Level.Template.pptx)

**Comment by jkarpen** [comment]
@ian-r-rose and I met and reviewed the items in the risk tracker. Next steps I will talk to Jason about how he wants to report this up and Ian and I will check back on the list on a monthly basis for updates.
