### ISSUE TITLE
MDSA service templates

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#32]
In order to have a repeatable process for MDSA DIF projects, we should generate some useful templates for projects

## Project management templates

There are several points during a project lifecycle that could benefit from having some templates for helping manage the project. These might be coda, google docs, or airtable:

- [x] @jasonlally @britt-allen brainstorm jam
- [x] Britt to fill out the [discovery page](https://coda.io/d/_dY5Oul8-jdi/Discovery_su3gt)
- [x] Britt to fill out the [project charter page](https://coda.io/d/MDSA-Service-Template_dY5Oul8-jdi/Project-Charter_suRPs#_luXBG)
- [x] Britt to create a table to capture data and systems information
- [x] Britt to create [tools checklist](https://coda.io/d/MDSA-Service-Template_dY5Oul8-jdi/Tools-Checklist_suZB7#_luZY6)
- [x] [Hand-off plans](https://coda.io/d/MDSA-Service-Template_dY5Oul8-jdi/Hand-off-Plan_suCZL#_luPes) - steps for making sure that code, cloud infrastructure, and processes are transitioned to the partner entity.
- [x] Project assessment template - identify whether a partner is a good fit for our stack and maturity.
- [x] https://github.com/cagov/data-infrastructure/issues/24

## Code templates

Depending upon the project, it will often be useful to have some *code* template projects to quickly stand-up MDSA projects in GitHub. I've used [cookiecutter](https://github.com/cookiecutter/cookiecutter) for this in the past, though other approaches could work as well. These projects would allow us to quickly get

* Basic directory structure for a project
* testing framework boilerplate
* pre-commit setups for linting and code-quality
* Basic configuration files
* Documentation skeletons.

There are a number of ways we could structure MDSA project code strucutre, either as separate repos or as a monorepo that addresses different components of a project. In a lot of ways, I'm thinking that a monorepo might be easiest from an organizational perspective (CalData currently has separate repos, but I might want to merge them). Whether we organize as a monorepo or not, the templates might include:

- [x] A dbt project for data modeling
- [ ] ~~An orchestration project (Airflow or equivalent, cf #4) for data loading and scheduling of jobs~~ (Not planned right now)
- [ ] ~~A terraform project for standing up cloud resources in a replicable and auditable way.~~ (Not planned right now)
