### ISSUE TITLE
MDSA training drafts

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#49]
## Training templates

Training documents and templates for the MDSA. [Brainstorm/planning Gdoc](https://docs.google.com/document/d/1_wCaQ1jCLpZkWr-lSvVG-5invtEUb4GGrIfiu8-qFM4/edit#):

- [x] https://github.com/cagov/data-infrastructure/pull/77
- [x] https://github.com/cagov/data-infrastructure/issues/54
- [x] https://github.com/cagov/data-infrastructure/issues/53
- [x] https://github.com/cagov/data-infrastructure/issues/55
