### ISSUE TITLE
Cataloging tools intro + demo calls, evaluation criteria, and related flups

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#63]
- [x] Fill out Select * [sizing sheet ](https://docs.google.com/spreadsheets/d/1JxdawmbViijYFUlW9jcQR8PyXpEtwl60/edit#gid=1353240221) 
- [x] schedule internal debrief call
- [x] 5 demo calls
- [x] flup to each vendor
- [x] data analysis of eval criteria sent by each vendor
