### ISSUE TITLE
DIF - DOF data study

### ISSUE THREAD

**Issue by britt-allen** [cagov/data-infrastructure#88]
- [ ] building footprints - data study + write up
- [ ] census data - data study + write up
- [x] https://github.com/cagov/data-infrastructure/issues/90
- [x] https://github.com/cagov/data-infrastructure/issues/104 (script [here](https://github.com/cagov/data-orchestration/blob/a368f58519d24ee487ff3ce4f9b23111b333dfb6/dags/geo_reference/core.py#L13-L24))
- [x] https://github.com/cagov/data-infrastructure/issues/105 (script [here](https://github.com/cagov/data-orchestration/blob/a368f58519d24ee487ff3ce4f9b23111b333dfb6/dags/geo_reference/core.py#L13-L24))
- [x] https://github.com/cagov/data-infrastructure/issues/106
